import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { Pacifico } from "next/font/google";

import "./globals.css";
import Navbar from "../components/common/Navbar";
import Footer from "@/components/common/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const pacifico = Pacifico({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-pacifico",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${pacifico.variable} font-sans antialiased`}
      >
        <Navbar />
        <div>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
